config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  resource :session, only: [ :new, :create, :destroy ]
  resources :accounts do
    post :follow, on: :member
    resources :tweets, only: [ :new, :create ] do
      post :favorite, on: :member
      delete :unfavorite, on: :member
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # ツイート
  has_many :tweets, dependent: :destroy

  # フォローしているユーザー
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships

  # フォロワー
  has_many :followerships, :class_name => 'Friendship', :foreign_key => :friend_id, dependent: :destroy
  has_many :followers, :through => :followerships, :source => :account

  # ファボ
  has_many :favoriteships, dependent: :destroy
  has_many :favorite_tweets, :through => :favoriteships, :source => :tweet

  attr_accessor :password, :password_confirmation, :setting_password
  alias_method :setting_password?, :setting_password

  validates :password, presence: true, confirmation: true, on: :create
  validates_uniqueness_of :identify_name, on: :create
  validates :identify_name, format: { with: /\A[a-z0-9]+\z/i, allow_blank: true }

  before_save do
    if setting_password?
      self.password_digest = BCrypt::Password.create(password)
    end
  end

  def authenticate(raw_password)
    if password_digest && BCrypt::Password.new(password_digest) == raw_password
      self
    else
      false
    end
  end

  def not_follow_list
    not_display_ids = []
    not_display_ids << friends.map(&:id)
    not_display_ids << self.id
    Account.where.not(id: not_display_ids)
  end

  def normal_time_line
    timeline = []
    timeline << self.tweets
    self.friends.each do |friend|
      timeline << friend.tweets
    end
    timeline.flatten!
    timeline.sort_by{|obj| obj.created_at}.reverse
  end

  def favorited?(timeline_tweet)
    favorite_tweets = []
    favorite_tweets << self.favorite_tweets
    favorite_tweets.flatten!
    favorite_tweets.include?(timeline_tweet)
  end
end

app/models/favoriteship.rb
class Favoriteship < ActiveRecord::Base
  belongs_to :account
  belongs_to :tweet
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :account
  belongs_to :friend, :class_name => 'Account', :foreign_key => :friend_id
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :account
  has_many :favoriteships, :dependent => :destroy
  has_many :favorite_users, :through => :favoriteships, :source => :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate_account

  def new
    # @account = Account.new
    # render 'top/index'
  end

  def create
    @account = Account.new(account_params)
    @account.setting_password = true
    if @account.save
      flash[:notice] = "新規登録！ようこそ！#{@account.nickname}さん(^^)/"
      session[:current_user_id] = @account.id
    else
      flash[:alert] = "エラー！"
    end
    redirect_to :root
  end

  def follow
    Friendship.create(:account => current_user, :friend_id => params[:id])
    redirect_to :root
  end

  private
  def account_params
    params.require(:account).permit(
      :nickname, :identify_name,
      :password, :password_confirmation
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_account

  private
  def current_user
    if current_user_id = session[:current_user_id]
    #if current_user_id = cookies.signed[:current_user_id] || session[:current_user_id]
      @current_user = Account.find_by(id: current_user_id)
      session.delete(:current_user_id) unless @current_user
    end
    @current_user
  end
  helper_method :current_user

  def authenticate_account
    unless current_user
      redirect_to [ :new, :session ]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_account
  def new
    if current_user
      redirect_to :root
    else
      @account = Account.new
      render 'top/index'
    end
  end

  def create
    if user = UserPasswordAuthenticator.verify(params[:identify_name], params[:password])
      flash.notice = "ログインしました。こんにちは、#{user.nickname}さん(^o^)/"
      session[:current_user_id] = user.id
    else
      flash.alert = "ログインに失敗しました。"
    end
    redirect_to :root
  end

  def destroy
    # cookies.delete(:current_user_id)
    session.delete(:current_user_id)
    flash.notice = 'ログアウトしました。'
    redirect_to :root
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @account = Account.new
    @accounts = current_user.not_follow_list
    @tweet = Tweet.new
    @timeline = current_user.normal_time_line
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def favorite
    Favoriteship.create(:account => current_user, :tweet_id => params[:id] )
    redirect_to :root
  end

  def unfavorite
    @favorited_tweet = current_user.favoriteships.find_by(tweet_id: params[:id])
    if @favorited_tweet.delete
      flash.notice = "お気に入り解除しました。"
    else
      flash.alert = "処理に失敗しました。"
    end
    redirect_to :root
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      flash[:notice] = "ツイートしました"
    else
      flash[:alert] = "エラー！"
    end
    redirect_to :root
  end

  private
  def tweet_params
    params.require(:tweet).permit(
      :body
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/top/_time_line.html.erb
<% @timeline.each do |tl| %>
  <div class="timeline_tweet_box">
    <span class="font_thinly">
      <%= tl.account.nickname %>@<%= tl.account.identify_name %><br>
    </span>
    <%= tl.body %><br>
    <% if current_user.favorited?(tl) %>
      <%= link_to "★ ", [ :unfavorite, current_user, tl ], method: :delete %>
    <% else %>
      <%= link_to "☆ ", [ :favorite, current_user, tl ], method: :post %>
    <% end %>
    <span class="font_thinly">
      <%= tl.created_at.strftime('%Y年%m月%d日%H時%M分') %><br>
    </span>
  </div>
<% end %>

app/views/top/_user.html.erb
<h4>
  <div class="user_short_info">
    マイプロフィール<br>
    ニックネーム:<%= current_user.nickname %>
    ユーザーID:<%= current_user.identify_name %><br>
    フォロー:<%= current_user.friends.count %>
    フォロワー:<%= current_user.followers.count %>
    ツイート数:<%= current_user.tweets.count %>
    お気に入り数:<%= current_user.favorite_tweets.count %><br>
  </div>
  <div class="user_tweet_box">
    <h3>つぶやく</h3>
    <%= form_for @tweet, url: [ current_user, :tweets ], method: :post do |f| %>
      <%= f.text_area :body, :size => "32x10" %>
      <%= f.submit "ツイート" %>
    <% end %>
  </div>
</h4>

<div class="recommend_user_box">
  <h3>ユーザー一覧</h3>
  <% @accounts.each do |user| %>
    <%= user.nickname %>/<%= user.identify_name %>
    <%= link_to "フォロー", [ :follow, user ], method: :post %><br>
  <% end %>
</div>

app/views/top/index.html.erb
<h1>Twitter半日でどこまでできるかシリーズ</h1>

<% if current_user %>
  <%= link_to "ログアウト", :session, method: :delete %>
  <div class="account_ui_box">
    <div class="box_user">
      <%= render 'user' %>
    </div>
    <div class="box_tl">
      <%= render 'time_line' %>
    </div>
  </div>
<% else %>
  <h2>新規登録</h2>
  <table>
  <%= form_for @account, url: accounts_path, method: :post do |f| %>
    <tr>
      <th><%= f.label :nickname, "ニックネーム" %></th>
      <th><%= f.text_field :nickname %></th>
    </tr>
    <tr>
      <th><%= f.label :identify_name, "ID(後から変更できません), ※半角英数字のみ" %></th>
      <th><%= f.text_field :identify_name %></th>
    </tr>
    <tr>
      <th><%= f.label :password, "パスワード" %></th>
      <th><%= f.password_field :password %></th>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation, "パスワード再入力" %></th>
      <th><%= f.password_field :password_confirmation %></th>
    </tr>

    <tr>
      <th><%= f.submit "登録" %></th>
    </tr>
  </table>
  <% end %>

  <br>
  <h2>ログイン</h2>
  <%= form_tag [ :session ] do %>
    <%= label_tag :identify_name, "ID" %>
    <%= text_field_tag :identify_name %>
    <%= label_tag :password, 'パスワード' %>
    <%= password_field_tag :password %>
    <%= submit_tag 'Login' %>
  <% end %>
<% end %>